-- MySQL Script generated by MySQL Workbench
-- seg 24 jun 2019 11:08:13 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistema-avaliacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema-avaliacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema-avaliacao` DEFAULT CHARACTER SET utf8 ;
USE `sistema-avaliacao` ;

-- -----------------------------------------------------
-- Table `sistema-avaliacao`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-avaliacao`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `cpf` INT UNSIGNED NOT NULL,
  `tipo` ENUM('professor', 'aluno', 'administrador') NOT NULL,
  `nome` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sistema-avaliacao`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-avaliacao`.`turma` (
  `idturma` INT NOT NULL AUTO_INCREMENT,
  `disciplina` VARCHAR(60) NOT NULL,
  `codigo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idturma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sistema-avaliacao`.`usuario_has_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-avaliacao`.`usuario_has_turma` (
  `usuario_idusuario` INT NOT NULL,
  `turma_idturma` INT NOT NULL,
  PRIMARY KEY (`usuario_idusuario`, `turma_idturma`),
  INDEX `fk_usuario_has_turma_turma1_idx` (`turma_idturma` ASC),
  INDEX `fk_usuario_has_turma_usuario_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_usuario_has_turma_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `sistema-avaliacao`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_turma_turma1`
    FOREIGN KEY (`turma_idturma`)
    REFERENCES `sistema-avaliacao`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sistema-avaliacao`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-avaliacao`.`avaliacao` (
  `idavaliacao` INT NOT NULL AUTO_INCREMENT,
  `turma_idturma` INT NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idavaliacao`, `turma_idturma`),
  INDEX `fk_avaliacao_turma1_idx` (`turma_idturma` ASC),
  CONSTRAINT `fk_avaliacao_turma1`
    FOREIGN KEY (`turma_idturma`)
    REFERENCES `sistema-avaliacao`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sistema-avaliacao`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-avaliacao`.`grupo` (
  `idgrupo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT 'grupo',
  `tamanho` INT NULL DEFAULT 0,
  `avaliacao_idavaliacao` INT NOT NULL,
  `avaliacao_turma_idturma` INT NOT NULL,
  PRIMARY KEY (`idgrupo`, `avaliacao_idavaliacao`, `avaliacao_turma_idturma`),
  INDEX `fk_grupo_avaliacao1_idx` (`avaliacao_idavaliacao` ASC, `avaliacao_turma_idturma` ASC),
  CONSTRAINT `fk_grupo_avaliacao1`
    FOREIGN KEY (`avaliacao_idavaliacao` , `avaliacao_turma_idturma`)
    REFERENCES `sistema-avaliacao`.`avaliacao` (`idavaliacao` , `turma_idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sistema-avaliacao`.`indicador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-avaliacao`.`indicador` (
  `idindicador` INT NOT NULL AUTO_INCREMENT,
  `descricao-indicador` VARCHAR(80) NOT NULL,
  `resposta` VARCHAR(150) NULL,
  `situacao` TINYINT(1) NULL DEFAULT 0,
  `grupo_idgrupo` INT NOT NULL,
  `grupo_avaliacao_idavaliacao` INT NOT NULL,
  `grupo_avaliacao_turma_idturma` INT NOT NULL,
  PRIMARY KEY (`idindicador`, `grupo_idgrupo`, `grupo_avaliacao_idavaliacao`, `grupo_avaliacao_turma_idturma`),
  INDEX `fk_indicador_grupo1_idx` (`grupo_idgrupo` ASC, `grupo_avaliacao_idavaliacao` ASC, `grupo_avaliacao_turma_idturma` ASC),
  CONSTRAINT `fk_indicador_grupo1`
    FOREIGN KEY (`grupo_idgrupo` , `grupo_avaliacao_idavaliacao` , `grupo_avaliacao_turma_idturma`)
    REFERENCES `sistema-avaliacao`.`grupo` (`idgrupo` , `avaliacao_idavaliacao` , `avaliacao_turma_idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
