-- MySQL Script generated by MySQL Workbench
-- ter 25 jun 2019 08:58:39 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sistema-avaliacao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema-avaliacao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema-avaliacao` DEFAULT CHARACTER SET utf8 ;
USE `sistema-avaliacao` ;

-- -----------------------------------------------------
-- Table `sistema-avaliacao`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-avaliacao`.`admin` (
  `idadmin` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sistema-avaliacao`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-avaliacao`.`aluno` (
  `idaluno` INT NOT NULL AUTO_INCREMENT,
  `matricula-aluno` INT(14) UNSIGNED NOT NULL,
  `turma` VARCHAR(70) NULL,
  `email-aluno` VARCHAR(45) NULL,
  PRIMARY KEY (`idaluno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sistema-avaliacao`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-avaliacao`.`professor` (
  `idprofessor` INT NOT NULL AUTO_INCREMENT,
  `matricula-professor` INT(7) UNSIGNED NOT NULL,
  `email-professor` VARCHAR(50) NULL,
  PRIMARY KEY (`idprofessor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sistema-avaliacao`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-avaliacao`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(1) NOT NULL,
  `login` INT UNSIGNED NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  `cpf` INT UNSIGNED NULL,
  `nome` VARCHAR(120) NOT NULL,
  `admin_idadmin` INT NOT NULL,
  `aluno_idaluno` INT NOT NULL,
  `professor_idprofessor` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `admin_idadmin`, `aluno_idaluno`, `professor_idprofessor`),
  INDEX `fk_usuario_admin1_idx` (`admin_idadmin` ASC),
  INDEX `fk_usuario_aluno1_idx` (`aluno_idaluno` ASC),
  INDEX `fk_usuario_professor1_idx` (`professor_idprofessor` ASC),
  CONSTRAINT `fk_usuario_admin1`
    FOREIGN KEY (`admin_idadmin`)
    REFERENCES `sistema-avaliacao`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `sistema-avaliacao`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_professor1`
    FOREIGN KEY (`professor_idprofessor`)
    REFERENCES `sistema-avaliacao`.`professor` (`idprofessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sistema-avaliacao`.`turma-virtual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-avaliacao`.`turma-virtual` (
  `idturma-virtual` INT NOT NULL AUTO_INCREMENT,
  `disciplina` VARCHAR(60) NOT NULL,
  `codigo` VARCHAR(10) NOT NULL,
  `professor_idprofessor` INT NOT NULL,
  PRIMARY KEY (`idturma-virtual`, `professor_idprofessor`),
  INDEX `fk_turma-virtual_professor1_idx` (`professor_idprofessor` ASC),
  CONSTRAINT `fk_turma-virtual_professor1`
    FOREIGN KEY (`professor_idprofessor`)
    REFERENCES `sistema-avaliacao`.`professor` (`idprofessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sistema-avaliacao`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-avaliacao`.`avaliacao` (
  `idavaliacao` INT NOT NULL AUTO_INCREMENT,
  `turma_idturma-virtual` INT NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idavaliacao`, `turma_idturma-virtual`),
  INDEX `fk_avaliacao_turma1_idx` (`turma_idturma-virtual` ASC),
  CONSTRAINT `fk_avaliacao_turma1`
    FOREIGN KEY (`turma_idturma-virtual`)
    REFERENCES `sistema-avaliacao`.`turma-virtual` (`idturma-virtual`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sistema-avaliacao`.`indicador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-avaliacao`.`indicador` (
  `idindicador` INT NOT NULL AUTO_INCREMENT,
  `descricao-indicador` VARCHAR(80) NOT NULL,
  `resposta` VARCHAR(150) NULL,
  `situacao` TINYINT(1) NULL DEFAULT 0,
  `nota` FLOAT NULL,
  `avaliacao_idavaliacao` INT NOT NULL,
  `avaliacao_turma_idturma-virtual` INT NOT NULL,
  PRIMARY KEY (`idindicador`, `avaliacao_idavaliacao`, `avaliacao_turma_idturma-virtual`),
  INDEX `fk_indicador_avaliacao1_idx` (`avaliacao_idavaliacao` ASC, `avaliacao_turma_idturma-virtual` ASC),
  CONSTRAINT `fk_indicador_avaliacao1`
    FOREIGN KEY (`avaliacao_idavaliacao` , `avaliacao_turma_idturma-virtual`)
    REFERENCES `sistema-avaliacao`.`avaliacao` (`idavaliacao` , `turma_idturma-virtual`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `sistema-avaliacao`.`aluno_has_turma-virtual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema-avaliacao`.`aluno_has_turma-virtual` (
  `aluno_idaluno` INT NOT NULL,
  `turma-virtual_idturma-virtual` INT NOT NULL,
  PRIMARY KEY (`aluno_idaluno`, `turma-virtual_idturma-virtual`),
  INDEX `fk_aluno_has_turma-virtual_turma-virtual1_idx` (`turma-virtual_idturma-virtual` ASC),
  INDEX `fk_aluno_has_turma-virtual_aluno1_idx` (`aluno_idaluno` ASC),
  CONSTRAINT `fk_aluno_has_turma-virtual_aluno1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `sistema-avaliacao`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_has_turma-virtual_turma-virtual1`
    FOREIGN KEY (`turma-virtual_idturma-virtual`)
    REFERENCES `sistema-avaliacao`.`turma-virtual` (`idturma-virtual`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
